<a href="https://colab.research.google.com/github/rajeshxdatascience/Car-Price-Prediction-ML/blob/main/01_Exploratory_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/CAR DETAILS FROM CAR DEKHO.csv")

In [3]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [6]:
df[df.duplicated()]

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
13,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
14,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
16,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
17,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4307,Mahindra Xylo H4,2019,599000,15000,Diesel,Individual,Manual,Third Owner
4308,Maruti Alto 800 LXI,2018,200000,35000,Petrol,Individual,Manual,First Owner
4309,Datsun GO Plus T,2017,350000,10171,Petrol,Dealer,Manual,First Owner
4310,Renault Duster 110PS Diesel RxL,2015,465000,41123,Diesel,Dealer,Manual,First Owner
4311,Toyota Camry Hybrid 2.5,2017,1900000,20118,Petrol,Dealer,Automatic,First Owner

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3577 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           3577 non-null   object
 1   year           3577 non-null   int64
 2   selling_price  3577 non-null   int64
 3   km_driven      3577 non-null   int64
 4   fuel           3577 non-null   object
 5   seller_type    3577 non-null   object
 6   transmission   3577 non-null   object
 7   owner          3577 non-null   object
dtypes: int64(3), object(5)
memory usage: 251.5+ KB

In [11]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [15]:
df['name'].value_counts()

name
Maruti Swift Dzire VDI        54
Maruti Alto 800 LXI           48
Maruti Alto LXi               42
Maruti Alto LX                30
Maruti Swift VDI BSIV         28
                              ..
Tata Indica V2 DLS BSII        1
Mahindra XUV500 W10 AWD        1
Toyota Fortuner 2.7 2WD AT     1
Fiat Punto EVO 1.3 Emotion     1
Nissan Terrano XE 85 PS        1
Name: count, Length: 1491, dtype: int64

In [20]:
df['brand'] = df['name'].str.lower().str.split(' ').str.get(0)

In [21]:
df['brand'].value_counts()

brand
maruti           1072
hyundai           637
mahindra          328
tata              308
ford              220
honda             216
toyota            170
chevrolet         151
renault           110
volkswagen         93
nissan             52
skoda              49
fiat               32
audi               31
datsun             29
bmw                25
mercedes-benz      21
mitsubishi          5
jaguar              5
land                5
volvo               4
jeep                3
ambassador          3
opelcorsa           2
mg                  2
force               1
daewoo              1
isuzu               1
kia                 1
Name: count, dtype: int64

In [28]:
brands_counts = df['brand'].value_counts()

rare_brands = brands_counts[brands_counts < 20].index

df['brand'] = df['brand'].replace(rare_brands, 'other')

In [29]:
df['brand'].value_counts()

brand
maruti           1072
hyundai           637
mahindra          328
tata              308
ford              220
honda             216
toyota            170
chevrolet         151
renault           110
volkswagen         93
nissan             52
skoda              49
others             33
fiat               32
audi               31
datsun             29
bmw                25
mercedes-benz      21
Name: count, dtype: int64

In [31]:
df = df.drop('name', axis=1)

In [32]:
df.head()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,maruti
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,maruti
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,hyundai
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,datsun
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,honda

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3577 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           3577 non-null   int64
 1   selling_price  3577 non-null   int64
 2   km_driven      3577 non-null   int64
 3   fuel           3577 non-null   object
 4   seller_type    3577 non-null   object
 5   transmission   3577 non-null   object
 6   owner          3577 non-null   object
 7   brand          3577 non-null   object
dtypes: int64(3), object(5)
memory usage: 251.5+ KB

In [34]:
df['car_age'] = 2026 - df['year']

In [36]:
df['car_age'].value_counts()

car_age
9     346
14    338
11    332
12    321
13    298
8     295
10    283
15    247
16    210
17    169
7     162
18    129
19    117
20     93
21     61
6      45
22     38
23     22
24     18
25     16
26     12
27      9
28      9
29      3
30      2
31      1
34      1
Name: count, dtype: int64

In [39]:
df = df.drop('year',axis=1)

In [40]:
df.head()

,selling_price,km_driven,fuel,seller_type,transmission,owner,brand,car_age
0,60000,70000,Petrol,Individual,Manual,First Owner,maruti,19
1,135000,50000,Petrol,Individual,Manual,First Owner,maruti,19
2,600000,100000,Diesel,Individual,Manual,First Owner,hyundai,14
3,250000,46000,Petrol,Individual,Manual,First Owner,datsun,9
4,450000,141000,Diesel,Individual,Manual,Second Owner,honda,12

In [44]:
df.duplicated().sum()

np.int64(27)

In [45]:
df.drop_duplicates(inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3550 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   selling_price  3550 non-null   int64
 1   km_driven      3550 non-null   int64
 2   fuel           3550 non-null   object
 3   seller_type    3550 non-null   object
 4   transmission   3550 non-null   object
 5   owner          3550 non-null   object
 6   brand          3550 non-null   object
 7   car_age        3550 non-null   int64
dtypes: int64(3), object(5)
memory usage: 249.6+ KB

In [47]:
df.head()

,selling_price,km_driven,fuel,seller_type,transmission,owner,brand,car_age
0,60000,70000,Petrol,Individual,Manual,First Owner,maruti,19
1,135000,50000,Petrol,Individual,Manual,First Owner,maruti,19
2,600000,100000,Diesel,Individual,Manual,First Owner,hyundai,14
3,250000,46000,Petrol,Individual,Manual,First Owner,datsun,9
4,450000,141000,Diesel,Individual,Manual,Second Owner,honda,12